services:
  - type: web
    name: my-application
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
         "RGNK~ka5K2ko1"
      - key: DATABASE_URL
        postgresql://myapp_user:CdortVYp1eUL4udSKse5M5Fhpew77Cp2@dpg-d1j5oare5dus73cuvc00-a/myapp_db_fcta
          name: my-database
          property: connectionString
